### ISSUE TITLE
KiriKiri .soc scripts

### ISSUE THREAD

**Issue by RedEye13** [arcusmaximus/VNTranslationTools#104] opened 2023-01-04 14:51 UTC
I found a game with this odd .soc extension for the script it's not encrypted 

I tried working around it by just replacing the extension into .ks and it did sort of work

only it copied the first line 5 times and it didn't detect the names

here's the script hopefully it's not a hassle to solve this

[scenario.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10345056/scenario.zip)

**Comment by RedEye13** [comment] 2023-01-04 22:50
I didn't think this warranted a new issue since the solution for it is mostly the same I found another KiriKiri game with an odd way to call the names in the script it has an "m" next to every name so VNTextPatch is ignoring the names.

[scenario.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10348012/scenario.zip)

I hope this doesn't come off as me complaining I really like this tool and just want it to improve.

**Comment by arcusmaximus** [comment] 2023-01-04 23:24
For the .soc scripts, which file has the duplicate lines? I don't see any at first sight. Also, are you sure the duplication is caused by VNTextPatch? (Maybe the lines are in fact duplicated in the .soc files?)

For the second game, the "m" prefix is a bit too short to assume it'll always indicate a name. In other games, this same prefix might be used for something completely different, which would cause VNTextPatch to import garbage into the translation file. Because this convention is so specific to this particular game, I won't be adding it into the "official" source code - please add it yourself. (VNTextPatch is open source specifically to allow for this kind of customization)

**Comment by RedEye13** [comment] 2023-01-05 01:09
So yeah for the first thing about the .soc my bad I didn't check more than one file but yeah this one is definitely getting duplicated by VNTextPatch I've included both the original and the JSON for you my guess is it's getting confused because there's code after that line before the script resumes 
[__testbu.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10348499/__testbu.zip)

as for the second issue, it's actually present in all of https://vndb.org/p467 cataloge well almost all the last 2 games didn't have the m prefix not sure if that affects your decision as for me personally I can deal with it on my own no problem :)

**Comment by arcusmaximus** [comment] 2023-01-05 14:24
> this one is definitely getting duplicated by VNTextPatch

I opened the .ks file to see this:

```
[voice file="A0001_001" ]
[talk name="緋沙音"]
「おはよう、アナタ。今日も一日頑張って欲しいから／
頑張ってみたの」
[hitret ]

[FcActMove layer=1 pos=1438 y=&-1840 time=10000   ]

[voice file="A0001_001" ]
[talk name="緋沙音"]
「おはよう、アナタ。今日も一日頑張って欲しいから／
頑張ってみたの」
[hitret ]

[voice file="A0001_001" ]
[talk name="緋沙音"]
「おはよう、アナタ。今日も一日頑張って欲しいから／
頑張ってみたの」
[hitret ]

[voice file="A0001_001" ]
[talk name="緋沙音"]
「おはよう、アナタ。今日も一日頑張って欲しいから／
頑張ってみたの」
[hitret ]

[voice file="A0001_001" ]
[talk name="緋沙音"]
「おはよう、アナタ。今日も一日頑張って欲しいから／
頑張ってみたの」
[hitret ]
```

> as for the second issue, it's actually present in all of https://vndb.org/p467 cataloge 

It's not so much that it's not worth adding the prefix for these games. As mentioned, the main issue I have is that it could cause problems for other games.

I made VNTextPatch recognize the .soc extension and the "talk" command, but I'll leave it at that for this ticket.

**Closed by arcusmaximus** 2023-01-05 14:24 UTC
